---
- name: Download k3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/get-k3s.sh
    mode: '0755'

- name: Execute k3s installation script
  ansible.builtin.command: /tmp/get-k3s.sh
  args:
    creates: /usr/local/bin/k3s  # 👈 Якщо K3s уже встановлено, крок автоматично пропуститься

- name: Ensure k3s service is started and enabled
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true

- name: Create .kube directory for ubuntu user
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy k3s kubeconfig to ubuntu user home
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: '0600'

- name: Symlink k3s to kubectl
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link
