replicaCount: 3

image:
  repository: nginxdemos/hello
  tag: plain-text
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  path: /
  pathType: Prefix
