name: Continuous Deployment (GitOps)

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy-helm:
    name: Deploy Helm Chart to K3s
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Helm Chart
        run: |
          echo "===> Deploying Helm Chart..."
          helm upgrade --install my-demo ./k8s/demo-app-chart \
            --namespace demo-app \
            --create-namespace

      - name: Check deployment status
        run: |
          echo "===> Checking deployment status..."
          kubectl rollout status deployment/my-demo-app -n demo-app --timeout=60s
